stages:
  data_preprocessing:
    cmd: python scripts/data_prep_script.py
    deps:
      - scripts/data_prep_script.py
      - src/data_prep.py
      - data/raw/bitext-retail-ecommerce-llm-chatbot-training-dataset.csv
      - configs/data_prep_config.yaml
    params:
      - sampling.sample_size
      - sampling.sample_description
    outs:
      - data/processed/latest_dataset_ref.json:
          persist: true

  fine_tuning:
    cmd: >-
      python scripts/fine_tuning_script.py 
      --input-ref data/processed/latest_dataset_ref.json 
      --output-dir results/ 
      --config params.yaml 
      --mlflow-uri https://dagshub.com/ShenghaoisYummy/E-commerce-Chatbot.mlflow
    deps:
      - scripts/fine_tuning_script.py
      - src/fine_tuning.py
      - params.yaml
      - data/processed/latest_dataset_ref.json
    params:
      - model
      - lora
      - training
      - data
    outs:
      - results/model_location.json:
          persist: true

  evaluation:
      cmd: >-
      python scripts/evaluation_script.py 
      --input-ref data/evaluation/evaluation_10rows.csv
      --model-artifact-path results/model_location.json
      --output-dir results/evaluations
      --config params.yaml
      --mlflow-uri https://dagshub.com/ShenghaoisYummy/E-commerce-Chatbot.mlflow
    deps:
      - scripts/evaluation_script.py
      - src/evaluation.py
      - data/evaluation/evaluation_10rows.csv
      - results/evaluations
    params:
      - evaluation
    metrics:
      - results/evaluations/metrics.json:
          cache: false
