# Parameters for DVC pipeline

# Data preprocessing parameters
sampling:
  sample_size: 10
  sample_description: "small_dataset_for_testing_pipeline"

# Model configuration
model:
  base_model: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
  device:
    use_gpu: true
    precision: "float32"
    device_map: "auto"
    load_in_8bit: false

# LoRA configuration
lora:
  r: 16
  alpha: 32
  dropout: 0.05
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"

# Training configuration
training:
  epochs: 2
  batch_size: 4
  gradient_accumulation_steps: 4
  learning_rate: 0.0005
  weight_decay: 0.01
  warmup_steps: 100
  max_length: 512
  fp16: true
  bf16: false
  eval_strategy: "epoch"
  save_strategy: "epoch"
  save_total_limit: 2
  load_best_model_at_end: true

# Data configuration
data:
  dataset_path: "data/processed/chatml_dataset_fine_tuning_dataset.jsonl"
  test_size: 0.1
  seed: 42
  text_column: "text"

# Evaluation configuration
evaluation:
  use_dagshub: true
  batch_size: 4
  max_length: 512
  num_beams: 4
  metrics:
    - "bleu"
    - "rouge"

# Deployment configuration
deployment:
  min_improvement_threshold: 0.001 # Minimum improvement required for deployment
  model_registry_name: "ecommerce-chatbot" # MLflow model registry name
  huggingface:
    model_id: "ShenghaoYummy/TinyLlama-ECommerce-Chatbot"
    push_to_hub: true
    create_model_card: true
  weighted_scoring:
    weights:
      bleu1: 0.10 # 10% - Basic vocabulary coverage
      bleu2: 0.15 # 15% - Phrase fluency
      bleu3: 0.25 # 25% - Local grammar structure
      bleu4: 0.40 # 40% - Overall quality (most important)
      rougeL_precision: 0.10 # 10% - Long sequence precision

# MLflow configuration
mlflow:
  tracking_uri: "https://dagshub.com/ShenghaoisYummy/E-commerce-Chatbot.mlflow"
  experiment_name: "ecommerce-chatbot-evaluation"
