# Add to configs/base_config.yaml or create configs/eval_config.yaml

# Evaluation configuration
evaluation:
  use_dagshub: true # Set to true to load model from DagShub/MLflow
  model_path: "ShenghaoYummy/145a05ed" # Fallback model path if DagShub loading fails
  eval_dataset_path: "data/evaluation/evaluation_10rows.csv" # Evaluation dataset
  sample_size: 100 # How many samples to evaluate (set to null to use entire test set)
  metrics:
    - "bleu"
    - "rouge"

# MLflow configuration for evaluation
mlflow:
  tracking_uri: "https://dagshub.com/ShenghaoisYummy/E-commerce-Chatbot.mlflow"
  experiment_name: "ecommerce-chatbot-evaluation"
