# Parameters for DVC pipeline

# Data preprocessing parameters
sampling:
  sample_size: 10
  sample_description: "small_dataset_for_testing_pipeline"

# Model configuration
model:
  base_model: "deepseek-ai/deepseek-coder-1.3b-instruct"
  load_in_8bit: false

# LoRA configuration
lora:
  r: 16
  alpha: 32
  dropout: 0.1
  target_modules:
    - "q_proj"
    - "v_proj"
    - "k_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"

# Training configuration
training:
  epochs: 1
  batch_size: 1
  gradient_accumulation_steps: 1
  learning_rate: 2.0e-4
  weight_decay: 0.01
  warmup_steps: 100
  max_length: 256
  fp16: false
  eval_strategy: "epoch"
  save_strategy: "epoch"
  save_total_limit: 2
  load_best_model_at_end: true

# Data configuration
data:
  dataset_path: "data/processed/processed_dataset_10rows_small_dataset_for_testing_pipeline_20250502_132555.csv"
  test_size: 0.1
  seed: 42
  instruction_column: "instruction"
  response_column: "response"

# Evaluation configuration
evaluation:
  use_dagshub: true
  model_path: "ShenghaoYummy/145a05ed"
  eval_dataset_path: "data/evaluation/evaluation_10rows.csv"
  sample_size: 100
  metrics:
    - "bleu"
    - "rouge"

# MLflow configuration
mlflow:
  tracking_uri: "https://dagshub.com/ShenghaoisYummy/E-commerce-Chatbot.mlflow"
  experiment_name: "ecommerce-chatbot-evaluation"
